[build]
  command = "pnpm install --no-frozen-lockfile && NODE_ENV=production pnpm --filter @workspace/animex build"
  publish = "artifacts/animex/dist/public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
